### ISSUE TITLE
[Consulta] Stores y Actions

### ISSUE THREAD

**Issue by andresatencio** [platzi/ejemplo-reflux#1]
@slifszyc Muy bueno el tutorial de platzi. Te queria consultar acerca de un concepto que no estoy entendiendo muy bien, ya que en el readme del repo dice que las Actions representan acciones como peticiones ajax, pero en el tutorial veo que la petición esta realizada en el Store. Desde ya muchas gracias, y felicitaciones por el tuto.

**Comment by sachalifs** [comment]
Hola Andrés, muchas gracias!

Te comento, ambas opciones son válidas. Usando [Reflux](https://github.com/spoike/refluxjs), los Stores tienen la función `trigger()` que facilita eso.

Hay mucha discusión sobre dónde tiene que estar el llamado async hacia el server: si en las acciones, en los stores o totalmente fuera de ellos.

Acá te paso un video donde debaten un poco sobre este tema.

Por otro lado, por ejemplo, con [Redux](https://github.com/gaearon/redux) una versión de Flux hecha por @gaearon se hace algo totalmente distinto donde no existen los Stores, y son más bien Reducers.

Acá su video en React Europe: https://www.youtube.com/watch?v=xsSnOQynTHs

Espero que te haya servido de ayuda, saludos!
